---
- hosts: all
  sudo: yes
  vars:
    OPENFIRE_URL: "{{ OPENFIRE_URL }}"
    OPENFIRE_PACKAGE: "{{ OPENFIRE_PACKAGE }}"
    DB_USER: "{{ DB_USER }}"
    DB_PASSWORD: "{{ DB_PASSWORD }}"
    DB_NAME: "{{ DB_NAME }}"

  roles:
    - vagrantbox
    - java
    - openfire
    - postgresql
